# Generated by Django 4.2.17 on 2025-01-08 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=10)),
                ('date', models.DateField()),
                ('sales_growth', models.FloatField()),
                ('equity_growth', models.FloatField()),
                ('eps_growth', models.FloatField()),
                ('fcf_growth', models.FloatField()),
                ('roic', models.FloatField()),
            ],
        ),
    ]
